### PR TITLE
Issue 457: fixed problems with probabilities

### PR DESCRIPTION
**Pull request by JRustyHaner**
hintLevel probabilities was not being passed to selectCard, which it now is. If hintLevelProbabilites return less than 0, null, or NaN, an error will be thrown,

### CODE REVIEW

**Comment by imrryr** [comment]
This is confusing to me, the error should be thrown if the probability is null or NaN, the hintlevel should not need to be set, that is a bug now.

**Comment by imrryr** [comment]
I'll let you back this out

**Comment by JRustyHaner** [comment]
How hintlevel is being set hasn't changed. The hintlevel calculation wasn't being used to determine which hintlevel is displayed to the user. hintlevelProbabilities just wasn't being used. This was causing the NaNs.

**Comment by imrryr** [comment]
So, in Meng's work this won't cause problems? Since her hint level will be undefined right? Thus it will be null.

**Comment by JRustyHaner** [comment]
There shouldn't be a case where hintLevel is undefined, since the default hintlevel is 0. I'll hotfix something extra to make sure though.

**Comment by imrryr** [comment]
OK, sound good. Just was thinking of backward compatibility when you said that about throwing an error

**Pull request merged**
