### PR TITLE
Issue 752: Review timeout taking too long

### LINKED ISSUE #752: Review timeout taking too long
Review timeout is taking too long to the point that there are 2-3 seconds after the timer finishes where the system is still hung up on something. 

More visible with meng's tdfs.

### PR DESCRIPTION
**Pull request by MegaGeese**
Index calculations were still not running synchronously with the review timeout. Now they are synchronous. 

Review timeout can be bottle-necked by index calculations if they take too long (i.e index calculations take 3 seconds but review timeout takes 2 means that the system wont progress for an extra second).

closes #752

### CODE REVIEW

**Comment by imrryr** [comment]
So, should Meng be trying this again?

**Comment by MegaGeese** [comment]
Yes. Calculating indices takes about 2-3 seconds so correct response might still take one second longer but incorrect response shouldnt take longer than expected.

**Comment by MegaGeese** [comment]
I've profiled the calculateIndices function and there were several unoptimal decisions made. Several instances of triple nested for-loops. I've gotten the index calculations down too 900ms from 2500-3000ms with basic optimizations.

**Comment by imrryr** [comment]
Wow!

**Pull request merged**
