### PR TITLE
Issue 414: added download option

### LINKED ISSUE #414: Ability to download stims/tdfs from postgres (admins/teachers)
Allow downloading tdfs/stims from file content uploader for convenience of bug testing.

### PR DESCRIPTION
**Pull request by JRustyHaner**
Case: 
Go to content uploader, click the download button under uploaded files.
closes #414

### CODE REVIEW

**Review by MegaGeese — CHANGES_REQUESTED** [review]
- TDF Download returns a file with the only contents being [Object object]. This could be because the file contents are being sent as json instead of being converted to a strings. 
 - Stims dont run when reuploaded after being downloaded. 
 - Stim files only have one stim permuted multiple times.

**Comment by JRustyHaner** [comment]
works now, thanks

**Review by MegaGeese — CHANGES_REQUESTED** [review]
Since tdfs are coming from the db there is extra data inside the downloaded files that is not necessary and will cause sessions to crash if they were re-uploaded.

**Comment by JRustyHaner** [comment]
@MegaGeese

**Pull request merged**
