### PR TITLE
ISS1126: Levels of Deployment

### PR DESCRIPTION
**Pull request by JRustyHaner**
Allows for local authoring not using aolney's server with docker

### CODE REVIEW

**Comment by aolney** [comment]
@JRustyHaner Could you please elaborate? It looks like the code in the commit is an old version of my code. I changed it to use local endpoints at your request ~3 months ago, see here:

https://github.com/aolney/mofacts-automated-authoring/blob/6187963eeb738da98523e89973ae48e6511a690e/src/AllenNLP.fs#L166

Let me know if you'd like me to change the above code to your new format.

**Comment by JRustyHaner** [comment]
Local endpoints do not work well with docker, since docker used a virtual network so each endpoint has it's own hostname that corresponds to the name of the container.

Do the names look correct for the endpoints?

For example, the /predicts endpoints are for Allen NLP?

**Comment by aolney** [comment]
Yes they look correct to me

**Comment by JRustyHaner** [comment]
> Yes they look correct to me

@aolney all of it is running on the machine learning tower we have in the office. I haven't tried to author anything yet, but all the containers report back working.

**Pull request merged**
