### PR TITLE
disable progress report when tag is set

### LINKED ISSUE #477: Option to make student progress report unavailable in some tdfs
So, it occurs to me the progress reporter should be unavailable in some learning systems like Meng's. Do we support that?

### PR DESCRIPTION
**Pull request by JRustyHaner**
fixes #477 .

In setspec, there is now a parameter called "disableProgressReport". if set to true, the option to select that tdf in the progress report will be disabled, with the option displaying <tdf display name> (progress report disabled).

I added this parameter to Testing Tdf, also adding it to the wiki.

### CODE REVIEW

**Comment by imrryr** [comment]
@JRustyHaner @MegaGeese Does this need to merged in?

**Comment by JRustyHaner** [comment]
@imrryr  This is legacy for postgres migration that was never merged. We can create this feature again on staging if you still want it to be implemented.

**Comment by imrryr** [comment]
Yes please.

**Comment by JRustyHaner** [comment]
This is fixes in PR #1265

**Pull request closed without merging**
